#!/usr/bin/env python3
"""
NER-SAFE — COMPONENT 12: STEP 2 (CORRECTED)
Automated SDMA & Lifeline Advisory Bulletins Generator
Scientific Research Prototype — Spatial Guidance & Consequence Analysis
Author: NER-SAFE Research & Development Team
Date: September 2026
"""

import os
import json
import csv

PROJECT_ROOT = r"E:\landslide - Copy\landslide - Copy"
C11_DIR = os.path.join(PROJECT_ROOT, "NER_SAFE_DATA", "COMPONENT_11")
C12_DIR = os.path.join(PROJECT_ROOT, "NER_SAFE_DATA", "COMPONENT_12")

BULLETINS_DIR = os.path.join(C12_DIR, "bulletins")
os.makedirs(BULLETINS_DIR, exist_ok=True)

print("=" * 80)
print("NER-SAFE — COMPONENT 12: STEP 2 — SDMA ADVISORY BULLETINS GENERATOR (AUDITED)")
print("=" * 80)

# Load event records
events_csv_fp = os.path.join(C11_DIR, "events", "event_records.csv")
events = []
with open(events_csv_fp, "r", encoding="utf-8") as f:
    for row in csv.DictReader(f):
        events.append(row)

# Filter by state
meghalaya_events = [e for e in events if e["state"] == "Meghalaya"]
mizoram_events = [e for e in events if e["state"] == "Mizoram"]

DISCLAIMER_BANNER = [
    "> [!IMPORTANT]",
    "> **RESEARCH PROTOTYPE NOTICE & STATUTORY LIMITATION**:",
    "> This bulletin is an automated experimental decision-support advisory generated by the NER-SAFE research prototype (SIH 26001).",
    "> - **No Time-of-Failure Prediction**: Slope stability depends on local geotechnical, hydrologic, and micro-topographic conditions not captured by regional satellite/DEM models.",
    "> - **Consequence Estimations**: Road lengths and building counts represent spatial intersections with empirical DEM runout corridors, NOT field-verified ground damage.",
    "> - **Statutory Authority**: This system possesses NO statutory authority. Evacuations, highway closures, traffic diversions, and emergency deployments rest solely with the State Disaster Management Authorities and District Emergency Operation Centers under the Disaster Management Act 2005.",
    ""
]

# -----------------------------------------------------------------------------
# 1. GENERATE MEGHALAYA ADVISORY BULLETIN
# -----------------------------------------------------------------------------
meg_critical = [e for e in meghalaya_events if e["impact_priority"] == "CRITICAL"]
meg_high = [e for e in meghalaya_events if e["impact_priority"] == "HIGH"]
meg_mod = [e for e in meghalaya_events if e["impact_priority"] == "MODERATE"]
meg_low = [e for e in meghalaya_events if e["impact_priority"] == "LOW"]

meg_bldgs = sum(int(e["buildings_exposed"]) for e in meghalaya_events)
meg_roads_m = sum(float(e["roads_exposed_length_m"]) for e in meghalaya_events)
meg_pop = sum(int(e["population_exposed"]) for e in meghalaya_events)

meg_lines = [
    "# MEGHALAYA STATE DISASTER MANAGEMENT ADVISORY",
    "## LANDSLIDE SUSCEPTIBILITY & EXPOSURE SITUATION BULLETIN (RESEARCH PROTOTYPE)",
    "",
    "**Issuing Authority**: NER-SAFE Decision-Support Research Platform (SIH 26001 / MDoNER)  ",
    "**Target State**: Government of Meghalaya — State & District Disaster Management Authorities  ",
    "**Bulletin Date**: September 7, 2026 | Time: 16:45 IST  ",
    "**Advisory Scope**: Experimental Regional Monitoring Baseline  ",
    "",
    "---",
    ""
]
meg_lines.extend(DISCLAIMER_BANNER)
meg_lines.extend([
    "### 1. State Summary & Modeled Exposure Metrics",
    f"- **Monitored Candidate Hotspots in Meghalaya**: {len(meghalaya_events)} slope locations",
    f"- **Priority Tier 1 (High Concern)**: **{len(meg_critical)} hotspots** (Intersecting major transport corridors or structures)",
    f"- **Priority Tier 2 (Elevated)**: **{len(meg_high)} hotspots** (Rural road proximity)",
    f"- **Priority Tier 3 (Watch)**: **{len(meg_mod)} hotspots** (Elevated antecedent moisture)",
    f"- **Priority Tier 4 (Low Signal)**: **{len(meg_low)} hotspots** (Low modeled signal; local factors unmonitored)",
    f"- **Estimated Exposed Road Length**: **{meg_roads_m:,.1f} meters** (Empirical runout intersections)",
    f"- **Potentially Intersected Building Footprints**: **{meg_bldgs} structures**",
    f"- **Potentially Exposed Residents**: **~{meg_pop} persons** (Census-derived spatial estimate)",
    "",
    "---",
    "",
    "### 2. High Concern (Tier 1) Slope Locations in Meghalaya",
    "| Event ID | District | Nearest Place | Elevation Drop | Modeled Corridor Area | Exposed Roads | Exposed Structures | Technical Assessment Note |",
    "| :--- | :--- | :--- | :---: | :---: | :---: | :---: | :--- |"
])

for e in meg_critical:
    roads_txt = f"{e['roads_exposed_length_m']} m ({e['exposed_road_names']})" if float(e['roads_exposed_length_m']) > 0 else "0 m"
    bldgs_txt = f"{e['buildings_exposed']} bldgs" if int(e['buildings_exposed']) > 0 else "0 bldgs"
    meg_lines.append(
        f"| **`{e['event_id']}`** | {e['district']} | {e['nearest_settlement']} | "
        f"{e['elevation_drop_m']} m | {int(float(e['runout_area_m2'])):,} m² | "
        f"{roads_txt} | {bldgs_txt} | "
        f"Recommend PWD/NHAI visual inspection along {e['exposed_road_names'] if e['exposed_road_names'] else 'local slopes'} |"
    )

meg_lines.extend([
    "",
    "---",
    "",
    "### 3. District-Level Advisory Guidance for Consideration",
    "1. **East Jaintia Hills**: Empirical runout models intersect segments of NH-06 near Khliehriat. Ground engineering teams are advised to monitor culverts, side drains, and cut-slope debris accumulation.",
    "2. **East Khasi Hills**: Hillside settlements near Pynursla and Sohra exhibit steep terrain gradients. Village Disaster Management Committees (VDMCs) should be encouraged to report visible tension cracks.",
    "3. **West Jaintia Hills & South West Khasi Hills**: Saturated soil conditions warrant general vigilance by field officers along rural connecting roads.",
    "",
    "---",
    "",
    "### 4. Technical Limitations & Data Lineage",
    "- **Terrain Model**: USGS SRTM 30m 1 arc-second DEM (2000).",
    "- **Dynamic Precipitation**: NASA GPM IMERG Daily Final V07 (~10 km native resolution).",
    "- **Soil Moisture**: NASA SMAP Level-3 (~9 km native resolution).",
    "- **Consequence Baseline**: OSM roads, building footprints, and Census 2011 demographics.",
    "- **Non-Deterministic Notice**: This advisory represents relative susceptibility and trigger anomalies, NOT a deterministic physical warning."
])

meg_report_fp = os.path.join(BULLETINS_DIR, "SDMA_Meghalaya_Situation_Report.md")
with open(meg_report_fp, "w", encoding="utf-8") as f:
    f.write("\n".join(meg_lines))
print(f"Saved {meg_report_fp}")

# -----------------------------------------------------------------------------
# 2. GENERATE MIZORAM ADVISORY BULLETIN
# -----------------------------------------------------------------------------
miz_critical = [e for e in mizoram_events if e["impact_priority"] == "CRITICAL"]
miz_high = [e for e in mizoram_events if e["impact_priority"] == "HIGH"]
miz_mod = [e for e in mizoram_events if e["impact_priority"] == "MODERATE"]
miz_low = [e for e in mizoram_events if e["impact_priority"] == "LOW"]

miz_bldgs = sum(int(e["buildings_exposed"]) for e in mizoram_events)
miz_roads_m = sum(float(e["roads_exposed_length_m"]) for e in mizoram_events)
miz_pop = sum(int(e["population_exposed"]) for e in mizoram_events)

miz_lines = [
    "# MIZORAM STATE DISASTER MANAGEMENT ADVISORY",
    "## LANDSLIDE SUSCEPTIBILITY & EXPOSURE SITUATION BULLETIN (RESEARCH PROTOTYPE)",
    "",
    "**Issuing Authority**: NER-SAFE Decision-Support Research Platform (SIH 26001 / MDoNER)  ",
    "**Target State**: Government of Mizoram — Disaster Management & Rehabilitation Department  ",
    "**Bulletin Date**: September 7, 2026 | Time: 16:45 IST  ",
    "**Advisory Scope**: Experimental Regional Monitoring Baseline  ",
    "",
    "---",
    ""
]
miz_lines.extend(DISCLAIMER_BANNER)
miz_lines.extend([
    "### 1. State Summary & Modeled Exposure Metrics",
    f"- **Monitored Candidate Hotspots in Mizoram**: {len(mizoram_events)} slope locations",
    f"- **Priority Tier 1 (High Concern)**: **{len(miz_critical)} hotspots** (Corridor proximity to transport or structures)",
    f"- **Priority Tier 2 (Elevated)**: **{len(miz_high)} hotspots**",
    f"- **Priority Tier 3 (Watch)**: **{len(miz_mod)} hotspots**",
    f"- **Priority Tier 4 (Low Signal)**: **{len(miz_low)} hotspots** (Low modeled signal; local factors unmonitored)",
    f"- **Estimated Exposed Road Length**: **{miz_roads_m:,.1f} meters** (Empirical runout intersections)",
    f"- **Potentially Intersected Building Footprints**: **{miz_bldgs} structures**",
    f"- **Potentially Exposed Residents**: **~{miz_pop} persons** (Census-derived spatial estimate)",
    "",
    "---",
    "",
    "### 2. High Concern (Tier 1) Slope Locations in Mizoram",
    "| Event ID | District | Nearest Place | Elevation Drop | Modeled Corridor Area | Exposed Roads | Exposed Structures | Technical Assessment Note |",
    "| :--- | :--- | :--- | :---: | :---: | :---: | :---: | :--- |"
])

for e in miz_critical:
    roads_txt = f"{e['roads_exposed_length_m']} m ({e['exposed_road_names']})" if float(e['roads_exposed_length_m']) > 0 else "0 m"
    bldgs_txt = f"{e['buildings_exposed']} bldgs" if int(e['buildings_exposed']) > 0 else "0 bldgs"
    miz_lines.append(
        f"| **`{e['event_id']}`** | {e['district']} | {e['nearest_settlement']} | "
        f"{e['elevation_drop_m']} m | {int(float(e['runout_area_m2'])):,} m² | "
        f"{roads_txt} | {bldgs_txt} | "
        f"Recommend local field verification along {e['exposed_road_names'] if e['exposed_road_names'] else 'hill slopes'} |"
    )

miz_lines.extend([
    "",
    "---",
    "",
    "### 3. District-Level Advisory Guidance for Consideration",
    "1. **Kolasib District**: Ridge cuts along NH-54 corridor exhibit modeled runout intersection. PWD highway patrol recommended to inspect road drainage.",
    "2. **Saiha District**: Steep scarp gradients near Kaochao 'E' intersect local road and residential structures. District authorities may consider site-level visual inspection.",
    "3. **Lunglei & Mamit**: Remote hillslopes require ongoing weather monitoring. Slower soil drainage in valleys should be monitored after persistent rains.",
    "",
    "---",
    "",
    "### 4. Technical Limitations & Data Lineage",
    "- **Model Lineage**: Component 10 Heuristic Gradient Boosted & Logistic Regression models + Component 11 D8 empirical steepest-descent routing.",
    "- **Resolution Constraints**: Regional-scale indicators cannot resolve localized engineering cuts, retaining wall conditions, or unmapped drainage blockages."
])

miz_report_fp = os.path.join(BULLETINS_DIR, "SDMA_Mizoram_Situation_Report.md")
with open(miz_report_fp, "w", encoding="utf-8") as f:
    f.write("\n".join(miz_lines))
print(f"Saved {miz_report_fp}")

# -----------------------------------------------------------------------------
# 3. GENERATE STRATEGIC LIFELINE CORRIDOR ADVISORY
# -----------------------------------------------------------------------------
lifeline_lines = [
    "# NER-SAFE STRATEGIC LIFELINE CORRIDOR HAZARD ADVISORY",
    "## TRANSPORTATION INFRASTRUCTURE VULNERABILITY REPORT (RESEARCH PROTOTYPE)",
    "",
    "**Issuing Authority**: NER-SAFE Decision-Support Research Platform (SIH 26001 / MDoNER)  ",
    "**Focus Corridors**: National Highway NH-06 (Meghalaya) & NH-54 (Mizoram)  ",
    "**Date**: September 7, 2026 | Scope: **Informational Infrastructure Guidance**  ",
    "",
    "---",
    ""
]
lifeline_lines.extend(DISCLAIMER_BANNER)
lifeline_lines.extend([
    "### 1. Corridor Focus #1: National Highway NH-06 (Shillong — Khliehriat — Silchar)",
    "**Strategic Context**: NH-06 is the primary transportation artery connecting Meghalaya to southern Assam (Barak Valley), Tripura, and Mizoram. Steep cut-slopes along the Jaintia Hills escarpment are susceptible to rainfall-induced erosion and slope failures.",
    "",
    "#### Monitored Candidate Hotspots Intersecting NH-06 Corridor:",
    "| Event ID | District | Latitude / Longitude | Modeled Risk | Exposed Road Length | Modeled Footprint | Technical Advisory Note |",
    "| :--- | :--- | :---: | :---: | :---: | :---: | :--- |"
])

for e in [x for x in events if x["state"] == "Meghalaya" and x["impact_priority"] == "CRITICAL"]:
    lifeline_lines.append(
        f"| **`{e['event_id']}`** | {e['district']} | `{e['latitude']}°N, {e['longitude']}°E` | "
        f"`{e['risk_score']}` | **{e['roads_exposed_length_m']} m** | {int(float(e['runout_area_m2'])):,} m² | "
        f"Recommend PWD/NHAI visual inspection of culvert discharge and road embankment |"
    )

lifeline_lines.extend([
    "",
    "---",
    "",
    "### 2. Corridor Focus #2: National Highway NH-54 (Vairengte — Kolasib — Aizawl)",
    "**Strategic Context**: NH-54 serves as a vital logistics route for northern and central Mizoram, traversing steep topography subject to monsoon saturation.",
    "",
    "#### Monitored Candidate Hotspots Intersecting NH-54 Corridor:",
    "| Event ID | District | Latitude / Longitude | Modeled Risk | Exposed Road Length | Modeled Footprint | Technical Advisory Note |",
    "| :--- | :--- | :---: | :---: | :---: | :---: | :--- |"
])

for e in [x for x in events if x["state"] == "Mizoram" and x["district"] == "Kolasib" and x["impact_priority"] == "CRITICAL"]:
    lifeline_lines.append(
        f"| **`{e['event_id']}`** | {e['district']} | `{e['latitude']}°N, {e['longitude']}°E` | "
        f"`{e['risk_score']}` | **{e['roads_exposed_length_m']} m** | {int(float(e['runout_area_m2'])):,} m² | "
        f"Recommend maintenance patrol check for tension cracks along hillward cut |"
    )

lifeline_lines.extend([
    "",
    "---",
    "",
    "### 3. Summary of Modeled Highway Intersections",
    f"- **Cumulative Modeled Highway Exposure**: **{meg_roads_m + miz_roads_m:,.1f} meters**",
    "- **Identified Corridors**: National Highway NH-06, NH-54, NH-306",
    "- **Operational Context**: Non-statutory spatial decision support. Traffic management remains the sole authority of District Police and Administration."
])

lifeline_fp = os.path.join(BULLETINS_DIR, "Lifeline_Corridor_Advisories.md")
with open(lifeline_fp, "w", encoding="utf-8") as f:
    f.write("\n".join(lifeline_lines))
print(f"Saved {lifeline_fp}")

# Mirror to project root
for fname in ["SDMA_Meghalaya_Situation_Report.md", "SDMA_Mizoram_Situation_Report.md", "Lifeline_Corridor_Advisories.md"]:
    src = os.path.join(BULLETINS_DIR, fname)
    dst = os.path.join(PROJECT_ROOT, fname)
    with open(src, "r", encoding="utf-8") as sf, open(dst, "w", encoding="utf-8") as df:
        df.write(sf.read())

print("Mirrored all bulletins to project root.")
print("=" * 80)
print("STEP 2 COMPLETE: 3 Authoritative Situation Bulletins audited and updated successfully!")
print("=" * 80)
